# -*- coding: utf-8 -*-
"""cloudpro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B-G6VeESJqAg8KvWIn0dmNo4IALh4_fO
"""

import numpy as np
from google.colab import files
from PIL import Image

test=files.upload()

im = Image.open('a..jpg')
width, height = im.size
pixel_values = list(im.getdata())

a=pixel_values[0]
a=np.array(a)

if(a[0]==a[1]==a[2]):
  print("Shade of black or white")
else:
  if(a[0]==a[1]):
    print("RED")
  elif((a[1]==a[2]) or (a[0]==a[2])):
    print("BLUE")
  else:
    x=np.argmax(a)
    if(x==0):
      print("RED")
    elif(x==1):
      print("GREEN")
    else:
      print("BLUE")